### Indexing

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.ones([1, 5, 5, 3])
print(a)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]], shape=(1, 5, 5, 3), dtype=float32)


In [3]:
a[0][0]

<tf.Tensor: id=11, shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a[0][0][0]

<tf.Tensor: id=24, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
a[0][0][0][2]

<tf.Tensor: id=41, shape=(), dtype=float32, numpy=1.0>

### Numpy-style indexing

In [6]:
a = tf.random.normal([4, 28, 28, 3])

In [7]:
a[1].shape

TensorShape([28, 28, 3])

In [8]:
a[1, 2].shape

TensorShape([28, 3])

In [9]:
a[1, 2, 3].shape

TensorShape([3])

In [10]:
a[1, 2, 3, 2].shape

TensorShape([])

In [11]:
a = tf.range(10)
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


### start:end

In [12]:
# 返回的是一个向量
print(a[-1:])

tf.Tensor([9], shape=(1,), dtype=int32)


In [13]:
print(a[-2:])

tf.Tensor([8 9], shape=(2,), dtype=int32)


In [14]:
print(a[:2])

tf.Tensor([0 1], shape=(2,), dtype=int32)


In [15]:
print(a[:-1])

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [16]:
# 返回的是一个标量！
print(a[-1])

tf.Tensor(9, shape=(), dtype=int32)


### indexing by :

In [18]:
a = tf.random.normal([4, 28, 28, 3])
a.shape

TensorShape([4, 28, 28, 3])

In [19]:
a[0].shape

TensorShape([28, 28, 3])

In [20]:
a[0, :, :, :].shape

TensorShape([28, 28, 3])

In [21]:
a[0, 1, :, :].shape

TensorShape([28, 3])

In [22]:
a[:, :, :, 0].shape

TensorShape([4, 28, 28])

In [23]:
a[:, :, :, 2].shape

TensorShape([4, 28, 28])

In [24]:
a[:, 2, :, :].shape

TensorShape([4, 28, 3])

In [25]:
# start:end:step
# ::step

a[0:2, :, :, :].shape

TensorShape([2, 28, 28, 3])

In [26]:
a[:, 0:28:2, 2:28:2, :].shape

TensorShape([4, 14, 13, 3])

In [27]:
a[:, :14, :14, :].shape

TensorShape([4, 14, 14, 3])

In [28]:
a[:, 14:, 14:, :].shape

TensorShape([4, 14, 14, 3])

In [29]:
a[:, ::2, ::2, :].shape

TensorShape([4, 14, 14, 3])

### ::-1

In [30]:
a = tf.range(4)
print(a)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [31]:
a[::-1]

<tf.Tensor: id=153, shape=(4,), dtype=int32, numpy=array([3, 2, 1, 0])>

In [32]:
a[::-2]

<tf.Tensor: id=158, shape=(2,), dtype=int32, numpy=array([3, 1])>

In [39]:
a[2::-2]

<tf.Tensor: id=193, shape=(2,), dtype=int32, numpy=array([2, 0])>

In [40]:
a[0::-2]

<tf.Tensor: id=198, shape=(1,), dtype=int32, numpy=array([0])>

In [41]:
a[1::-2]

<tf.Tensor: id=203, shape=(1,), dtype=int32, numpy=array([1])>

In [42]:
a[3::-2]

<tf.Tensor: id=208, shape=(2,), dtype=int32, numpy=array([3, 1])>

### ...

In [43]:
a = tf.random.normal([2, 4, 28, 28, 3])

In [44]:
a[0].shape

TensorShape([4, 28, 28, 3])

In [45]:
a[0, :, :, :, :].shape

TensorShape([4, 28, 28, 3])

In [46]:
a[0, ...].shape

TensorShape([4, 28, 28, 3])

In [47]:
a[:, :, :, :, 2].shape

TensorShape([2, 4, 28, 28])

In [48]:
a[..., 2].shape

TensorShape([2, 4, 28, 28])

In [49]:
a[0, ..., 2].shape

TensorShape([4, 28, 28])

In [50]:
a[1, 0, ..., 2].shape

TensorShape([28, 28])

### Selective indexing

In [56]:
a = tf.random.normal([4, 35, 8])

In [55]:
tf.gather(a, axis=0, indices=[2, 3]).shape

TensorShape([2, 35, 8])

In [57]:
a[2:4].shape

TensorShape([2, 35, 8])

In [58]:
# 收集顺序打散

tf.gather(a, axis=0, indices=[2,1,3,0]).shape

TensorShape([4, 35, 8])

In [59]:
tf.gather(a, axis=1, indices=[2,3,7,9,16]).shape

TensorShape([4, 5, 8])

In [60]:
tf.gather(a, axis=2, indices=[2,3,7]).shape

TensorShape([4, 35, 3])

### tf.gather_nd

In [61]:
a.shape

TensorShape([4, 35, 8])

In [62]:
tf.gather_nd(a, [0]).shape

TensorShape([35, 8])

In [63]:
tf.gather_nd(a, [0, 1]).shape

TensorShape([8])

In [67]:
tf.gather_nd(a, [0, 1, 2]).shape
print(tf.gather_nd(a, [0, 1, 2]))

tf.Tensor(1.2368828, shape=(), dtype=float32)


In [68]:
tf.gather_nd(a, [[0, 1, 2]]).shape
print(tf.gather_nd(a, [[0, 1, 2]]))

tf.Tensor([1.2368828], shape=(1,), dtype=float32)


In [69]:
tf.gather_nd(a, [[0, 0], [1, 1]]).shape

TensorShape([2, 8])

In [70]:
tf.gather_nd(a, [[0, 0], [1, 1], [2, 2]]).shape

TensorShape([3, 8])

In [72]:
tf.gather_nd(a, [[0, 0, 0], [1, 1, 1], [2, 2, 2]]).shape
print(tf.gather_nd(a, [[0, 0, 0], [1, 1, 1], [2, 2, 2]]))

tf.Tensor([ 0.61787057 -1.4067941  -0.0901957 ], shape=(3,), dtype=float32)


In [73]:
tf.gather_nd(a, [[[0, 0, 0], [1, 1, 1], [2, 2, 2]]]).shape
print(tf.gather_nd(a, [[[0, 0, 0], [1, 1, 1], [2, 2, 2]]]))

tf.Tensor([[ 0.61787057 -1.4067941  -0.0901957 ]], shape=(1, 3), dtype=float32)


### tf.boolean_mask

In [74]:
a = tf.random.normal([4, 28, 28, 3])

In [75]:
a.shape

TensorShape([4, 28, 28, 3])

In [78]:
tf.boolean_mask(a, mask=[True, True, False, False]).shape

TensorShape([2, 28, 28, 3])

In [79]:
tf.boolean_mask(a, mask=[True, True, False], axis=3).shape

TensorShape([4, 28, 28, 2])

In [80]:
a = tf.ones([2, 3, 4])
print(a)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [81]:
tf.boolean_mask(a, mask=[[True, False, False], [False, True, True]])

<tf.Tensor: id=471, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>