'''

Data Container:

list [1, 1.2, 'hello']

np.array [64, 224, 224, 3]  GPU not support

tf.Tensor 数据载体

tensor: rank > 2

TF computing lib

int, float, double;
bool;
string

'''

In [21]:
import os
import tensorflow as tf
import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [3]:
a = tf.constant(1)
print("a = ", a)

a =  tf.Tensor(1, shape=(), dtype=int32)


In [4]:
b = tf.constant(1.)
print("b = ", b)

b =  tf.Tensor(1.0, shape=(), dtype=float32)


In [5]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: id=5, shape=(), dtype=float64, numpy=2.0>

In [6]:
tf.constant([True, False])

<tf.Tensor: id=7, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [7]:
tf.constant('hello,world.')

<tf.Tensor: id=9, shape=(), dtype=string, numpy=b'hello,world.'>

In [8]:
with tf.device("cpu"):
    a = tf.constant([1])
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [9]:
with tf.device("gpu"):
    b = tf.range(4)
b.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [10]:
aa = a.gpu()
aa.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [11]:
bb = b.cpu()
bb.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [12]:
b.numpy()

array([0, 1, 2, 3])

In [13]:
b.ndim

1

In [14]:
tf.rank(b)

<tf.Tensor: id=19, shape=(), dtype=int32, numpy=1>

In [15]:
tf.rank(tf.ones([3, 4, 2]))

<tf.Tensor: id=24, shape=(), dtype=int32, numpy=3>

In [16]:
b.name

AttributeError: Tensor.name is meaningless when eager execution is enabled.

In [17]:
isinstance(a, tf.Tensor)

True

In [18]:
tf.is_tensor(b)

True

In [23]:
d = np.arange(4)
tf.is_tensor(d)

False

In [26]:
c = tf.constant('hello, world')
a.dtype, b.dtype, c.dtype, d.dtype

(tf.int32, tf.int32, tf.string, dtype('int32'))

In [31]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [32]:
a.dtype

dtype('int32')

In [35]:
aa = tf.convert_to_tensor(a)
print(aa)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [36]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)
print(aa)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [37]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: id=33, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [39]:
aaa = tf.cast(aa, dtype = tf.double)
print(aaa)

tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float64)


In [40]:
tf.cast(aaa, dtype=tf.int32)

<tf.Tensor: id=38, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [41]:
b = tf.constant([0, 1])
tf.cast(b, dtype=bool)

<tf.Tensor: id=41, shape=(2,), dtype=bool, numpy=array([False,  True])>

In [42]:
bb = tf.cast(b, dtype=tf.bool)
tf.cast(bb, tf.int32)

<tf.Tensor: id=44, shape=(2,), dtype=int32, numpy=array([0, 1])>

In [43]:
a = tf.range(5)
print(a)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [44]:
b = tf.Variable(a)

In [45]:
b.dtype

tf.int32

In [46]:
b.name

'Variable:0'

In [47]:
b = tf.Variable(a, name='input_data')

In [48]:
b.name

'input_data:0'

In [49]:
b.trainable

True

In [51]:
isinstance(b, tf.Tensor)

False

In [52]:
isinstance(b, tf.Variable)

True

In [53]:
tf.is_tensor(b)

True

In [54]:
b.numpy()

array([0, 1, 2, 3, 4])