In [1]:
import tensorflow as tf
import numpy as np

### Broadcasting

In [2]:
# expand
# without copying data
# tf.broadcast_to

'''
key idea

insert 1 dim ahead if needed

expand dims with size 1 to same siez

'''

x = tf.random.normal([4, 32, 32, 3])

In [3]:
(x + tf.random.normal([3])).shape

TensorShape([4, 32, 32, 3])

In [4]:
(x + tf.random.normal([32, 32, 1])).shape

TensorShape([4, 32, 32, 3])

In [5]:
(x + tf.random.normal([4, 1, 1, 1])).shape

TensorShape([4, 32, 32, 3])

In [6]:
(x + tf.random.normal([4, 4, 1, 1])).shape

InvalidArgumentError: Incompatible shapes: [4,32,32,3] vs. [4,4,1,1] [Op:Add] name: add/

In [7]:
x.shape

TensorShape([4, 32, 32, 3])

In [8]:
b = tf.broadcast_to(tf.random.normal([4, 1, 1, 1]), [4, 32, 32, 3])

In [9]:
b.shape

TensorShape([4, 32, 32, 3])

### Broadcast vs Tile

In [10]:
a = tf.ones([3, 4])

In [12]:
a1 = tf.broadcast_to(a, [2, 3, 4])
print(a1)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [18]:
a2 = tf.expand_dims(a, axis=0)
print(a2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 3, 4), dtype=float32)


In [19]:
a2 = tf.tile(a2, [2, 1, 1])
print(a2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
