In [2]:
import tensorflow as tf
import numpy as np

### pad

In [3]:
# pad[[A, B]]
# A代表左边填充个数， B代表右边填充个数

# pad[[0, 1], [1, 1]]

a = tf.reshape(tf.range(9), [3, 3])
print(a)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [4]:
tf.pad(a, [[0, 0], [0, 0]])

<tf.Tensor: id=8, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [5]:
tf.pad(a, [[1, 0], [0, 0]])

<tf.Tensor: id=11, shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [6]:
tf.pad(a, [[1, 1], [0, 0]])

<tf.Tensor: id=14, shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])>

In [7]:
tf.pad(a, [[1, 1], [1, 0]])

<tf.Tensor: id=17, shape=(5, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 1, 2],
       [0, 3, 4, 5],
       [0, 6, 7, 8],
       [0, 0, 0, 0]])>

In [9]:
tf.pad(a, [[1, 1], [1, 1]])

<tf.Tensor: id=23, shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])>

### image padding

In [10]:
a = tf.random.normal([4, 28, 28, 3])

In [11]:
b = tf.pad(a, [[0, 0], [2, 2], [2, 2], [0, 0]])

In [12]:
b.shape

TensorShape([4, 32, 32, 3])

### tile

In [14]:
# repeat data along dim n time
# [a, b, c], 2 => [a, b, c, a, b, c]
a = tf.reshape(tf.range(9), [3, 3])
print(a)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [15]:
tf.tile(a, [1, 2])

<tf.Tensor: id=42, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

In [16]:
tf.tile(a, [2, 1])

<tf.Tensor: id=45, shape=(6, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [17]:
tf.tile(a, [2, 2])

<tf.Tensor: id=48, shape=(6, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

In [18]:
aa = tf.expand_dims(a, axis=0)
print(aa.shape)

(1, 3, 3)


In [19]:
tf.tile(aa, [2, 1, 1])

<tf.Tensor: id=53, shape=(2, 3, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])>

In [20]:
tf.broadcast_to(aa, [2, 3, 3])

<tf.Tensor: id=56, shape=(2, 3, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])>