In [1]:
import tensorflow as tf

### clip_by_value

In [2]:
a = tf.reshape(tf.range(10), [10])
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [3]:
tf.maximum(a, 2)

<tf.Tensor: id=8, shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 9])>

In [4]:
tf.minimum(a, 8)

<tf.Tensor: id=11, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 8])>

In [5]:
# 两边限制

tf.clip_by_value(a, 2, 8)

<tf.Tensor: id=16, shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])>

### RELU

In [6]:
a = a - 5
print(a)

tf.Tensor([-5 -4 -3 -2 -1  0  1  2  3  4], shape=(10,), dtype=int32)


In [7]:
tf.nn.relu(a)

<tf.Tensor: id=21, shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>

In [8]:
tf.maximum(a, 0)

<tf.Tensor: id=24, shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>

### clip_by_norm

In [10]:
a = tf.random.normal([2, 2], mean=10)
print(a)

tf.Tensor(
[[ 9.383628  8.056662]
 [11.221519  8.909459]], shape=(2, 2), dtype=float32)


In [11]:
tf.norm(a)

<tf.Tensor: id=43, shape=(), dtype=float32, numpy=18.927843>

In [12]:
aa = tf.clip_by_norm(a, 15)
print(aa)

W0712 16:53:34.892783 11416 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\clip_ops.py:157: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


tf.Tensor(
[[7.436369 6.38477 ]
 [8.892867 7.060598]], shape=(2, 2), dtype=float32)


In [13]:
tf.norm(aa)

<tf.Tensor: id=67, shape=(), dtype=float32, numpy=14.999999>

### Gradient clipping

In [ ]:
# set lr=1
# new_grads, total_norm = tf.clip_by_gloabl_norm(grads, 25)