In [40]:
import tensorflow as tf
import numpy as np

### 向量范数 Vector Norm

In [3]:
a = tf.ones([2, 2])
print(a)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [4]:
# 二范数, 元素的平方和 开根号
tf.norm(a)

<tf.Tensor: id=11, shape=(), dtype=float32, numpy=2.0>

In [5]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: id=16, shape=(), dtype=float32, numpy=2.0>

In [6]:
a = tf.ones([4, 28, 28, 3])

In [7]:
tf.norm(a)

<tf.Tensor: id=25, shape=(), dtype=float32, numpy=96.99484>

In [8]:
tf.sqrt(tf.reduce_sum(tf.square(a)))

<tf.Tensor: id=30, shape=(), dtype=float32, numpy=96.99484>

### L1 Norm 一范数

In [16]:
b = tf.fill([2, 3], 2.)
print(b)

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)


In [17]:
tf.norm(b)

<tf.Tensor: id=68, shape=(), dtype=float32, numpy=4.8989797>

In [18]:
# axis =1  按列来算2范数， 一共2行，结果是2个

tf.norm(b, ord=2, axis=1)

<tf.Tensor: id=74, shape=(2,), dtype=float32, numpy=array([3.4641016, 3.4641016], dtype=float32)>

In [19]:
# 一范数， 所有元素的绝对值 求和

tf.norm(b, ord=1)

<tf.Tensor: id=79, shape=(), dtype=float32, numpy=12.0>

In [20]:
# axis=0， 按行结算1范数， 一共3列，结果是3个

tf.norm(b, ord=1, axis=0)

<tf.Tensor: id=84, shape=(3,), dtype=float32, numpy=array([4., 4., 4.], dtype=float32)>

In [21]:
tf.norm(b, ord=1, axis=1)

<tf.Tensor: id=89, shape=(2,), dtype=float32, numpy=array([6., 6.], dtype=float32)>

### reduce_min/max/mean

In [22]:
# 降维的过程

a = tf.random.normal([4, 10])

In [23]:
# 默认打平

tf.reduce_min(a), tf.reduce_max(a), tf.reduce_mean(a)

(<tf.Tensor: id=98, shape=(), dtype=float32, numpy=-2.4338684>,
 <tf.Tensor: id=100, shape=(), dtype=float32, numpy=2.6975565>,
 <tf.Tensor: id=102, shape=(), dtype=float32, numpy=0.0606529>)

In [24]:
tf.reduce_min(a, axis=1), tf.reduce_max(a, axis=1), tf.reduce_mean(a, axis=1)

(<tf.Tensor: id=107, shape=(4,), dtype=float32, numpy=array([-0.8704618, -2.3844569, -1.4844862, -2.4338684], dtype=float32)>,
 <tf.Tensor: id=109, shape=(4,), dtype=float32, numpy=array([2.4058518, 0.7022816, 1.9624331, 2.6975565], dtype=float32)>,
 <tf.Tensor: id=111, shape=(4,), dtype=float32, numpy=array([ 0.515371  , -0.539801  ,  0.3395246 , -0.07248294], dtype=float32)>)

### argmax / argmin

In [25]:
a.shape

TensorShape([4, 10])

In [26]:
# 最大值所在的位置
tf.argmax(a).shape

TensorShape([10])

In [27]:
tf.argmin(a)

<tf.Tensor: id=118, shape=(10,), dtype=int64, numpy=array([2, 3, 1, 3, 1, 1, 1, 2, 3, 3], dtype=int64)>

In [30]:
tf.argmin(a, axis=1)

<tf.Tensor: id=125, shape=(4,), dtype=int64, numpy=array([2, 8, 7, 8], dtype=int64)>

### tf.equal

In [31]:
a = tf.constant([1, 2, 3, 2, 5])

In [32]:
b = tf.range(5)
print(b)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [33]:
tf.equal(a, b)

<tf.Tensor: id=133, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [34]:
res = tf.equal(a, b)

In [35]:
# 把true false转换
tf.reduce_sum(tf.cast(res, dtype=tf.int32))

<tf.Tensor: id=138, shape=(), dtype=int32, numpy=0>

### Accuracy

In [47]:
a = tf.convert_to_tensor([[0.1, 0.2, 0.7], [0.9, 0.05, 0.05]])
print(a)

tf.Tensor(
[[0.1  0.2  0.7 ]
 [0.9  0.05 0.05]], shape=(2, 3), dtype=float32)


In [48]:
pred = tf.cast(tf.argmax(a, axis=1), dtype=tf.int32)
print(pred)

tf.Tensor([2 0], shape=(2,), dtype=int32)


In [49]:
y = tf.convert_to_tensor([2, 1])

In [50]:
tf.equal(y, pred)

<tf.Tensor: id=164, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [52]:
correct = tf.reduce_sum(tf.cast(tf.equal(y, pred), dtype=tf.int32))
print(correct)

tf.Tensor(1, shape=(), dtype=int32)


In [53]:
correct/2

<tf.Tensor: id=175, shape=(), dtype=float64, numpy=0.5>

### tf.unique

In [54]:
a = tf.range(5)

In [55]:
tf.unique(a)

Unique(y=<tf.Tensor: id=181, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>, idx=<tf.Tensor: id=182, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>)

In [56]:
a = tf.constant([4, 2, 2, 4, 3])

In [57]:
tf.unique(a)

Unique(y=<tf.Tensor: id=186, shape=(3,), dtype=int32, numpy=array([4, 2, 3])>, idx=<tf.Tensor: id=187, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)

In [2]:
# tf.gather(unique, idx)